
tech_corp_front_homepage:
    path:     /
    defaults: { _controller: TechCorpFrontBundle:Static:homepage }


tech_corp_front_about:
    path:     /about
    defaults: { _controller: TechCorpFrontBundle:Static:about }

tech_corp_front_test:
    path:     /test
    defaults: { _controller: TechCorpFrontBundle:Static:test }

tech_corp_front_timeline:
    path:     /timeline
    defaults: { _controller: TechCorpFrontBundle:Timeline:timeline }
